# Generated by Django 4.0 on 2022-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('series', models.CharField(max_length=100, verbose_name='Серия')),
                ('author', models.ForeignKey(on_delete=models.SET('Автор неизвестен'), to='main.author')),
            ],
        ),
    ]
